<?php
/**
 * Created S/19/03/2016
 * Updated D/24/05/2020
 *
 * Copyright 2008-2020 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * https://www.luigifab.fr/openmage/apijs
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */
?>

<?php if (Mage::getStoreConfigFlag('apijs/general/browser')):

	$data = $this->getBrowserData();

	if (!empty($data['browser']) && !empty($data['version'])) {
		$data['version'] = empty(Mage::app()->getRequest()->getParam('browser')) ? (float) $data['version'] : 1;
		if (($data['browser'] == 'MSIE') && ($data['version'] < 15)) {
			$text = $this->__('<strong>Warning:</strong> your browser <strong>%s %s</strong> is outdated, please <a %s>upgrade your browser</a>.', 'Internet Explorer', $data['version'], 'href="https://www.microsoft.com/windows/microsoft-edge"');
		}
		else if (($data['browser'] == 'Edge') && ($data['version'] < 16)) {
			$text = $this->__('<strong>Warning:</strong> your browser <strong>%s %s</strong> is outdated, please <a %s>upgrade your browser</a>.', 'Edge', $data['version'], 'href="https://www.microsoft.com/windows/microsoft-edge"');
		}
		else if (($data['browser'] == 'Firefox') && ($data['version'] < 36)) {
			$text = $this->__('<strong>Warning:</strong> your browser <strong>%s %s</strong> is outdated, please <a %s>upgrade your browser</a>.', 'Firefox', $data['version'], 'href="https://www.mozilla.org/firefox"');
		}
		else if (($data['browser'] == 'Chrome') && ($data['version'] < 31)) {
			$text = $this->__('<strong>Warning:</strong> your browser <strong>%s %s</strong> is outdated, please <a %s>upgrade your browser</a>.', 'Chrome', $data['version'], 'href="https://www.google.com/chrome"');
		}
		else if (($data['browser'] == 'Opera') && ($data['version'] < 19)) {
			$text = $this->__('<strong>Warning:</strong> your browser <strong>%s %s</strong> is outdated, please <a %s>upgrade your browser</a>.', 'Opera', $data['version'], 'href="https://www.opera.com/"');
		}
		else if (($data['browser'] == 'Safari') && ($data['version'] < 9)) {
			$text = $this->__('<strong>Warning:</strong> your browser <strong>%s %s</strong> is outdated, please <a %s>upgrade your browser</a>.', 'Safari', $data['version'], 'href="https://www.apple.com/safari/"');
		}
	}
?>
	<?php if (!empty($text)): ?>
		<div class="notification-global notification-global-error notification-global-apijs" id="oldBrowser"><?php echo $text ?></div>
	<?php endif ?>
<?php endif ?>