<?php
/**
 * Created J/12/09/2019
 * Updated V/12/06/2020
 *
 * Copyright 2008-2020 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * https://www.luigifab.fr/openmage/apijs
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */
?>

<?php echo $this->getChildHtml('wysiwyg_images.js') ?>
<script type="text/javascript">apijsOpenMage.overloadMediabrowser();</script>

<div class="content-header" id="content_header">
	<table cellspacing="0">
		<tr>
			<td><h3 class="icon-head"><?php echo $this->__('Media Storage') ?></h3></td>
			<td class="form-buttons">
				<?php echo str_replace('...', '', $this->getButtonsHtml()) ?>
				<button type="button" class="scalable add" onclick="apijsOpenMage.sendFiles(this.textContent, '<?php echo $this->getUrl('*/apijs_media/uploadWidget', ['form_key' => $this->getFormKey()]) ?>', <?php echo $this->helper('apijs')->getMaxSizes() ?>);">
					<span><?php echo $this->__('Add one or multiple files') ?></span>
				</button>
			</td>
		</tr>
	</table>
</div>

<div id="contents-loader" class="content-loader no-display"><?php echo $this->__('Please wait, loading...') ?></div>
<div id="contents"></div>
<div id="contents-uploader" class="no-display"></div>
<div id="contents-newfolder" class="no-display"><?php echo $this->getChildHtml('wysiwyg_images.newfolder') ?></div>