<?php
/**
 * Created D/20/11/2011
 * Updated J/04/11/2021
 *
 * Copyright 2008-2022 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * https://www.luigifab.fr/openmage/apijs
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$help = $this->helper('apijs');

// wysiwyg
$wysiwygDir      = $help->getWysiwygImageDir();
$wysiwygCacheDir = $help->getWysiwygImageDir(true);

if (is_dir($wysiwygCacheDir)) {

	exec('du -hs '.escapeshellarg($wysiwygCacheDir).' | cut -f1', $wysiwygCacheSize);
	$wysiwygCacheSize = trim(implode($wysiwygCacheSize));

	// 1G - 500M - 5M - 1.2M - 225K
	$size = (float) $wysiwygCacheSize;
	$size = $help->getNumber($size, ['precision' => 2]);
	if (stripos($wysiwygCacheSize, 'G') !== false)
		$wysiwygCacheSize = $this->__('%s GB', $size);
	else if (stripos($wysiwygCacheSize, 'M') !== false)
		$wysiwygCacheSize = $this->__('%s MB', $size);
	else if (stripos($wysiwygCacheSize, 'K') !== false)
		$wysiwygCacheSize = $this->__('%s kB', (int) $size);
	$wysiwygCacheSize = preg_replace('#[.,]00[[:>:]]#', '', $wysiwygCacheSize);
}
else {
	$wysiwygCacheSize = 0;
}

if (is_dir($wysiwygDir)) {

	exec('du -hs '.escapeshellarg($wysiwygDir).' --exclude='.escapeshellarg(basename($wysiwygCacheDir)).' | cut -f1', $wysiwygSize);
	$wysiwygSize = trim(implode($wysiwygSize));

	// 1G - 500M - 5M - 1.2M - 225K
	$size = (float) $wysiwygSize;
	$size = $help->getNumber($size, ['precision' => 2]);
	if (stripos($wysiwygSize, 'G') !== false)
		$wysiwygSize = $this->__('%s GB', $size);
	else if (stripos($wysiwygSize, 'M') !== false)
		$wysiwygSize = $this->__('%s MB', $size);
	else if (stripos($wysiwygSize, 'K') !== false)
		$wysiwygSize = $this->__('%s kB', (int) $size);
	$wysiwygSize = preg_replace('#[.,]00[[:>:]]#', '', $wysiwygSize);
}
else {
	$wysiwygSize = 0;
}

// produit
$catalogDir      = $help->getCatalogProductImageDir();
$catalogCacheDir = $help->getCatalogProductImageDir(true);

if (is_dir($catalogCacheDir)) {

	exec('du -hs '.escapeshellarg($catalogCacheDir).' | cut -f1', $catalogCacheSize);
	$catalogCacheSize = trim(implode($catalogCacheSize));

	// 1G - 500M - 5M - 1.2M - 225K
	$size = (float) $catalogCacheSize;
	$size = $help->getNumber($size, ['precision' => 2]);
	if (stripos($catalogCacheSize, 'G') !== false)
		$catalogCacheSize = $this->__('%s GB', $size);
	else if (stripos($catalogCacheSize, 'M') !== false)
		$catalogCacheSize = $this->__('%s MB', $size);
	else if (stripos($catalogCacheSize, 'K') !== false)
		$catalogCacheSize = $this->__('%s kB', (int) $size);
	$catalogCacheSize = preg_replace('#[.,]00[[:>:]]#', '', $catalogCacheSize);
}
else {
	$catalogCacheSize = 0;
}

if (is_dir($catalogDir)) {

	exec('du -hs '.escapeshellarg($catalogDir).' --exclude='.escapeshellarg(basename($catalogCacheDir)).' | cut -f1', $catalogSize);
	$catalogSize = trim(implode($catalogSize));

	// 1G - 500M - 5M - 1.2M - 225K
	$size = (float) $catalogSize;
	$size = $help->getNumber($size, ['precision' => 2]);
	if (stripos($catalogSize, 'G') !== false)
		$catalogSize = $this->__('%s GB', $size);
	else if (stripos($catalogSize, 'M') !== false)
		$catalogSize = $this->__('%s MB', $size);
	else if (stripos($catalogSize, 'K') !== false)
		$catalogSize = $this->__('%s kB', (int) $size);
	$catalogSize = preg_replace('#[.,]00[[:>:]]#', '', $catalogSize);
}
else {
	$catalogSize = 0;
}

// catégorie
$categoryDir      = $help->getCatalogCategoryImageDir();
$categoryCacheDir = $help->getCatalogCategoryImageDir(true);

if (is_dir($categoryCacheDir)) {

	exec('du -hs '.escapeshellarg($categoryCacheDir).' | cut -f1', $categoryCacheSize);
	$categoryCacheSize = trim(implode($categoryCacheSize));

	// 1G - 500M - 5M - 1.2M - 225K
	$size = (float) $categoryCacheSize;
	$size = $help->getNumber($size, ['precision' => 2]);
	if (stripos($categoryCacheSize, 'G') !== false)
		$categoryCacheSize = $this->__('%s GB', $size);
	else if (stripos($categoryCacheSize, 'M') !== false)
		$categoryCacheSize = $this->__('%s MB', $size);
	else if (stripos($categoryCacheSize, 'K') !== false)
		$categoryCacheSize = $this->__('%s kB', (int) $size);
	$categoryCacheSize = preg_replace('#[.,]00[[:>:]]#', '', $categoryCacheSize);
}
else {
	$categoryCacheSize = 0;
}

if (is_dir($categoryDir)) {

	exec('du -hs '.escapeshellarg($categoryDir).' --exclude='.escapeshellarg(basename($categoryCacheDir)).' | cut -f1', $categorySize);
	$categorySize = trim(implode($categorySize));

	// 1G - 500M - 5M - 1.2M - 225K
	$size = (float) $categorySize;
	$size = $help->getNumber($size, ['precision' => 2]);
	if (stripos($categorySize, 'G') !== false)
		$categorySize = $this->__('%s GB', $size);
	else if (stripos($categorySize, 'M') !== false)
		$categorySize = $this->__('%s MB', $size);
	else if (stripos($categorySize, 'K') !== false)
		$categorySize = $this->__('%s kB', (int) $size);
	$categorySize = preg_replace('#[.,]00[[:>:]]#', '', $categorySize);
}
else {
	$categorySize = 0;
}

// config
$values = $help->getMaxSizes(true);
?>

<?php if (Mage::getStoreConfigFlag('apijs/general/backend')): ?>
	<button type="button" onclick="apijs.dialog.dialogInformation('<?php echo $this->__('PHP manual') ?>','<?php echo addslashes($this->__('It is important to note that just because the mail was accepted for delivery, it doesn\'t mean the mail will actually reach the intended destination.')) ?>');"><?php echo $this->__('Example %d', 1) ?></button>
	<button type="button" onclick="apijs.dialog.dialogInformation('<?php echo $this->__('Surprise!') ?>','[p]<?php echo addslashes($this->__('You are watching this video without proprietary extension thanks to the new [em]video[/em] tag included in the [strong]HTML 5[/strong] language.')) ?>[/p][p]<?php echo addslashes($this->__('Website: %s', '[a href=\'https://www.luigifab.fr/\' class=\'popup\']www.luigifab.fr[/a]')) ?>[/p]');"><?php echo $this->__('Example %d', 2) ?></button>
<?php endif ?>

<div style="padding-left:6px; border-left:3px solid #AAA;">
	<?php if (Mage::getStoreConfigFlag('apijs/general/frontend')): ?>
		<p style="margin-top:1em;"><?php echo $this->__('You can use one of the following lines to test this module on the frontend:') ?></p>
		<code style="display:block; margin-bottom:0.8em; font-size:0.9em; line-height:1.4em;">
			{{block type="core/template" template="luigifab/apijs/demo.phtml"}}
			<br />&lt;block type="core/template" template="luigifab/apijs/demo.phtml" /&gt;
			<br />&lt;?php echo $this->getLayout()->createBlock('core/template')->setTemplate('luigifab/apijs/demo.phtml')->toHtml() ?&gt;
		</code>
	<?php endif ?>

	<p style="margin-top:1em;"><?php echo $this->__('Directories size:') ?></p>
	<ul style="margin-bottom:-1em; line-height:110%;">
		<li>
			<?php echo $wysiwygDir ?> <strong><?php echo $wysiwygSize ?></strong> (<?php echo $this->__('without cache') ?>)
		</li>
		<li>
			<?php echo $wysiwygCacheDir ?> <strong><?php echo $wysiwygCacheSize ?></strong>
			<?php if (Mage::getStoreConfigFlag('apijs/general/backend')): ?>
				(<button type="button" class="slink" onclick="apijsOpenMage.clearCache('<?php echo $this->getUrl('*/apijs_cache/clearCache', ['type' => 'wysiwyg']) ?>');"><?php echo $this->__('clear cache') ?></button>)
			<?php endif ?>
		</li>
		<li>
			<?php echo $catalogDir ?> <strong><?php echo $catalogSize ?></strong> (<?php echo $this->__('without cache') ?>)
		</li>
		<li>
			<?php echo $catalogCacheDir ?> <strong><?php echo $catalogCacheSize ?></strong>
			<?php if (Mage::getStoreConfigFlag('apijs/general/backend')): ?>
				(<button type="button" class="slink" onclick="apijsOpenMage.clearCache('<?php echo $this->getUrl('*/apijs_cache/clearCache', ['type' => 'product']) ?>');"><?php echo $this->__('clear cache') ?></button>)
			<?php endif ?>
		</li>
		<li>
			<?php echo $categoryDir ?> <strong><?php echo $categorySize ?></strong> (<?php echo $this->__('without cache') ?>)
		</li>
		<li>
			<?php echo $categoryCacheDir ?> <strong><?php echo $categoryCacheSize ?></strong>
			<?php if (Mage::getStoreConfigFlag('apijs/general/backend')): ?>
				(<button type="button" class="slink" onclick="apijsOpenMage.clearCache('<?php echo $this->getUrl('*/apijs_cache/clearCache', ['type' => 'category']) ?>');"><?php echo $this->__('clear cache') ?></button>)
			<?php endif ?>
		</li>
	</ul>

	<?php foreach ($values as $key => $value): ?>
		<br /><strong><?php echo $key ?></strong> = <?php echo $help->getNumberToHumanSize($value * 1024 * 1024) // de Mo à octets ?>
	<?php endforeach ?>
	<br /><strong>php max_file_uploads</strong> = <?php echo ini_get('max_file_uploads') ?>
	<br /><strong>exec</strong> <?php echo Mage::getSingleton('apijs/python')->getProgramVersions(
		'(jpg jpeg gif png, <a href="https://pillow.readthedocs.io/en/latest/">docs</a>)',
		'(svg, <a href="https://github.com/scour-project/scour/wiki/Documentation">docs</a>)') ?>
</div>

<hr style="margin:1em 0; border:0; border-top:1px solid #BBB;" />