<?php
/**
 * Created S/04/10/2014
 * Updated L/06/07/2020
 *
 * Copyright 2008-2020 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * Copyright 2019-2020 | Fabrice Creuzot <fabrice~cellublue~com>
 * https://www.luigifab.fr/openmage/apijs
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$product    = Mage::registry('current_product');
$attributes = $product->getMediaAttributes();
$maxWidth   = (int) Mage::getStoreConfig(Mage_Catalog_Helper_Image::XML_NODE_PRODUCT_MAX_DIMENSION);

$images = $product->getMediaGallery('images');
$images = empty($images) ? [] : $images;

$help = $this->helper('apijs');
$date = Mage::getSingleton('core/locale')->date();
$base = Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl();
$pid  = $product->getId();
$sid  = $product->getStoreId();
?>

<div class="grid" id="apijsGallery">
	<table cellspacing="0" class="data border gallery">
		<thead>
			<tr class="headings">
				<th><?php echo $this->__('Image'),'<br /><span>',$this->__('[GLOBAL]'),'</span>' ?></th>
				<th><?php echo $this->__('Label and Sort order'),'<br /><span>',$this->__('[STORE VIEW]'),'</span>' ?></th>
				<?php foreach ($attributes as $attribute): ?>
					<?php if ($attribute->getIsText() === true) continue; ?>
					<th class="attr"><?php
						echo $attribute->getFrontend()->getLabel(),'<br /><span>',$this->getScopeLabel($attribute),'</span>';
					?></th>
				<?php endforeach ?>
				<th class="attr" onclick="apijsOpenMage.toggleVisibility();">
					<?php echo $this->__('Exclude'),'<br /><span>',$this->__('[STORE VIEW]'),'</span>' ?>
				</th>
				<th class="attr last"></th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<td colspan="<?php echo count($attributes) + 4 ?>">
					<button type="button" class="scalable save" onclick="apijsOpenMage.actionSave('<?php echo $this->getSaveUrl() ?>');">
						<span><span><?php echo $this->__('Save images') ?></span></span>
					</button>
					<button type="button" class="scalable add" onclick="apijsOpenMage.sendFiles(this.textContent, '<?php echo $this->getAddUrl() ?>', <?php echo $help->getMaxSizes() ?>);">
						<span><span><?php echo $this->__('Add one or multiple files') ?></span></span>
					</button>
					<p><?php echo $this->__('The added or removed images are automatically saved.') ?>
					<br /><?php echo $this->__('Maximum images width and height is <a %s>%s x %s pixels</a>.',
						'href="'.$this->getUrl('*/system_config/edit', ['section' => 'catalog']).'"',
						Zend_Locale_Format::toNumber($maxWidth), Zend_Locale_Format::toNumber($maxWidth)) ?></p>
				</td>
			</tr>
		</tfoot>
		<tbody class="album" id="slideshow.0">
			<tr>
				<td><?php echo $this->__('No image') ?></td>
				<td></td>
				<?php foreach ($attributes as $code => $attribute): ?>
					<?php if ($attribute->getIsText() === true) continue; ?>
					<td>
						<?php // si dans eav_attribute, attribute_model = xyz/source_xyz ?>
						<?php // $attribute = Xyz_Xyz_Model_Source_Xyz extends Mage_Catalog_Model_Resource_Eav_Attribute ?>
						<?php if ($attribute->getIsCheckbox() !== true): ?>
							<?php if (!empty($sid)):
								$globalValue = $product->getResource()->getAttributeRawValue($pid, $code, 0);
								$storeValue  = $product->getResource()->getAttributeRawValue($pid, $code, $sid);
							?>
								<?php if (empty($globalValue) || ($globalValue == 'no_selection')): ?>
									<label>
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="checkbox" value="no_selection" <?php
											echo (empty($storeValue) || ($globalValue == 'no_selection')) ? 'checked="checked"' : '';
										?> disabled="disabled" />
									</label>
								<?php else: ?>
									<label style="visibility:hidden;">
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="checkbox" />
									</label>
								<?php endif ?>
								<label>
									<?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
									<input type="radio" name="apijs[<?php echo $code ?>]" value="no_selection" <?php
										echo ($storeValue == 'no_selection') ? 'checked="checked"' : '';
									?> />
								</label>
							<?php else: ?>
								<label>
									<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
									<input type="radio" name="apijs[<?php echo $code ?>]" value="no_selection" <?php
										echo (empty($product->getData($code)) || ($product->getData($code) == 'no_selection')) ?
											'checked="checked"' : '';
									?> />
								</label>
							<?php endif ?>
						<?php endif ?>
					</td>
				<?php endforeach ?>
				<td></td>
				<td class="last"></td>
			</tr>
			<?php $i = 0; foreach ($images as $image):
				$image = is_object($image) ? $image : new Varien_Object($image);
				$iid   = $image->getData('value_id');
				$path  = $image->getData('file');
				$file  = $help->getCatalogProductImageDir().$path;
				$label = $help->escapeEntities($image->getData('label'), true);
				$name  = $help->escapeEntities(basename($file), true);
			?>
				<tr id="attachmentId<?php echo $iid ?>">
					<td class="img" title="<?php echo $help->escapeEntities($path, true) ?>">
						<?php if (is_file($file)):
							// <a> <img src srcset> <input>
							// l'image du lien = une image redimensionnée en cache
							// l'image de l'image = une miniature en cache
						?>
							<a href="<?php echo $help->resizeImage($product, 'image', $path, 1200, 900, false) ?>" type="<?php echo mime_content_type($file) ?>" onclick="return false" id="slideshow.0.<?php echo $i++ ?>">
								<img src="<?php echo $help->resizeImage($product, 'thumbnail', $path, 200, 150, true) ?>" srcset="<?php echo $help->resizeImage($product, 'thumbnail', $path, 400, 300, true) ?> 2x" width="200" height="150" alt="<?php echo $label ?>" />
								<input type="hidden" value="<?php echo $name ?>|false|<?php echo $label ?>" />
							</a>
						<?php else: ?>
							<?php echo $this->__('File not found') ?>
						<?php endif ?>
					</td>
					<td>
						<div>
							<input type="hidden" name="apijs[<?php echo $iid ?>][file]" value="<?php echo $path ?>" />
							<div>
								<?php if (empty($sid)): ?>
									<label>
										<?php echo $this->__('Label') ?> /
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="text" name="apijs[<?php echo $iid ?>][label]" value="<?php echo $label ?>" maxlength="250" class="input-text val" />
									</label>
								<?php else: ?>
									<label>
										<?php echo $this->__('Label') ?> /
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="checkbox" name="apijs[<?php echo $iid ?>][label]" value="$$" <?php
											echo $this->isUseGlobal($image, 'label', 'checked');
										?> class="def inl" onchange="apijsOpenMage.checkVal(this);" />
									</label>
									<label>
										<input type="text" name="apijs[<?php echo $iid ?>][label]" value="<?php
											echo $help->escapeEntities(($image->getData('label') != $image->getData('label_default')) ?
												$image->getData('label') : $image->getData('label_default'), true);
										?>" <?php
											echo $this->isUseGlobal($image, 'label', 'disabled');
										?> maxlength="250" class="input-text val" />
									</label>
								<?php endif ?>
							</div>
							<div>
								<?php if (empty($sid)): ?>
									<label>
										<?php echo $this->__('Sort Order') ?> /
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="number" min="0" step="1" name="apijs[<?php echo $iid ?>][position]" value="<?php
											echo $image->getData('position');
										?>" class="input-text val" />
									</label>
								<?php else: ?>
									<label>
										<?php echo $this->__('Sort Order') ?> /
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="checkbox" name="apijs[<?php echo $iid ?>][position]" value="$$" <?php
											echo $this->isUseGlobal($image, 'position', 'checked');
										?> class="def inl" onchange="apijsOpenMage.checkVal(this);" />
									</label>
									<label>
										<input type="number" min="0" step="1" name="apijs[<?php echo $iid ?>][position]" value="<?php
											echo $help->escapeEntities(($image->getData('position') != $image->getData('position_default')) ?
												$image->getData('position') : $image->getData('position_default'), true);
										?>" <?php
											echo $this->isUseGlobal($image, 'position', 'disabled');
										?> class="input-text val" />
									</label>
								<?php endif ?>
							</div>
							<?php foreach ($attributes as $code => $attribute): ?>
								<?php if ($attribute->getIsText() !== true) continue; ?>
								<div>
									<?php // si dans eav_attribute, attribute_model = xyz/source_xyz ?>
									<?php // $attribute = Xyz_Xyz_Model_Source_Xyz extends Mage_Catalog_Model_Resource_Eav_Attribute ?>
									<?php if (empty($sid)): ?>
										<label>
											<?php echo $attribute->getData('frontend_label') ?> /
											<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
											<?php if ($attribute->getInputType() == 'number'): ?>
												<input type="number" min="0" step="1" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="<?php
													echo $image->getData($code);
												?>" class="input-text val" />
											<?php else: ?>
												<input type="text" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="<?php
													echo $image->getData($code);
												?>" class="input-text val" />
											<?php endif ?>
										</label>
									<?php else: ?>
										<label>
											<?php echo $attribute->getData('frontend_label') ?> /
											<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
											<input type="checkbox" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="$$" <?php
												echo $this->isUseGlobal($image, $code, 'checked');
											?> class="def inl" onchange="apijsOpenMage.checkVal(this);" />
										</label>
										<label>
											<?php if ($attribute->getInputType() == 'number'): ?>
												<input type="number" min="0" step="1" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="<?php
													echo $help->escapeEntities(($image->getData($code) != $image->getData($code.'_default')) ? $image->getData($code) : $image->getData($code.'_default'), true);
												?>" <?php
													echo $this->isUseGlobal($image, $code, 'disabled');
												?> class="input-text val" />
											<?php else: ?>
												<input type="text" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="<?php
													echo $help->escapeEntities(($image->getData($code) != $image->getData($code.'_default')) ? $image->getData($code) : $image->getData($code.'_default'), true);
												?>" <?php
													echo $this->isUseGlobal($image, $code, 'disabled');
												?> class="input-text val" />
											<?php endif ?>
										</label>
									<?php endif ?>
								</td>
							<?php endforeach ?>
						</div>
					</td>
					<?php foreach ($attributes as $code => $attribute): ?>
						<?php if ($attribute->getIsText() === true) continue; ?>
						<td>
							<?php // si dans eav_attribute, attribute_model = xyz/source_xyz ?>
							<?php // $attribute = Xyz_Xyz_Model_Source_Xyz extends Mage_Catalog_Model_Resource_Eav_Attribute ?>
							<?php if ($attribute->getIsCheckbox() === true): ?>
								<?php if (empty($sid)): ?>
									<label>
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="checkbox" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="1" <?php
											echo empty($image->getData($code)) ? '' : 'checked="checked"';
										?> />
									</label>
								<?php else: ?>
									<label>
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="checkbox" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="$$" <?php
											echo $this->isUseGlobal($image, $code, 'checked');
										?> class="def" onchange="apijsOpenMage.checkVal(this);" />
									</label>
									<label>
										<?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
										<input type="checkbox" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="1" <?php
											echo $image->getData($code) ? 'checked="checked"' : '';
										?> <?php
											echo $this->isUseGlobal($image, $code, 'disabled');
										?> class="val" />
									</label>
								<?php endif ?>
							<?php else: ?>
								<?php if (!empty($sid)):
									$globalValue = $product->getResource()->getAttributeRawValue($pid, $code, 0);
									$storeValue  = $product->getResource()->getAttributeRawValue($pid, $code, $sid);
								?>
									<?php if ($globalValue == $path): ?>
										<label>
											<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
											<input type="checkbox" <?php
												echo (empty($storeValue) || ($globalValue == $path)) ? 'checked="checked"' : '';
											?> disabled="disabled" />
										</label>
									<?php else: ?>
										<label style="visibility:hidden;">
											<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
											<input type="checkbox" />
										</label>
									<?php endif ?>
									<label>
										<?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
										<input type="radio" name="apijs[<?php echo $code ?>]" value="<?php echo $path ?>" <?php
											echo ($storeValue == $path) ? 'checked="checked"' : '';
										?> />
									</label>
								<?php else: ?>
									<label>
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="radio" name="apijs[<?php echo $code ?>]" value="<?php echo $path ?>" <?php
											echo ($product->getData($code) == $path) ? 'checked="checked"' : '';
										?> />
									</label>
								<?php endif ?>
							<?php endif ?>
						</td>
					<?php endforeach ?>
					<td>
						<?php if (empty($sid)): ?>
							<label>
								<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
								<input type="checkbox" name="apijs[<?php echo $iid ?>][disabled]" value="1" <?php
									echo $image->getData('disabled') ? 'checked="checked"' : '';
								?> class="val exclude" />
							</label>
						<?php else: ?>
							<label>
								<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
								<input type="checkbox" name="apijs[<?php echo $iid ?>][disabled]" value="$$" <?php
									echo $this->isUseGlobal($image, 'disabled', 'checked');
								?> class="def" onchange="apijsOpenMage.checkVal(this);" />
							</label>
							<label>
								<?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
								<input type="checkbox" name="apijs[<?php echo $iid ?>][disabled]" value="1" <?php
									echo $image->getData('disabled') ? 'checked="checked"' : '';
								?> <?php
									echo $this->isUseGlobal($image, 'disabled', 'disabled');
								?> class="val exclude" />
							</label>
						<?php endif ?>
					</td>
					<td class="last">
						<?php if (is_file($file)): ?>
							<a href="<?php echo $base,$path ?>" type="<?php echo mime_content_type($file) ?>" download=""><?php echo $this->__('Download') ?></a>
						<?php endif ?>
						<br /><button type="button" class="slink" onclick="apijsOpenMage.removeAttachment('<?php echo $this->getRemoveUrl($iid) ?>'); return false;"><?php echo $this->__('Remove') ?></button>

						<div style="margin-top:1em;"><?php if (is_file($file)) {
							$sizes = getimagesize($file);
							echo $help->getNumberToHumanSize(filesize($file)),
								'<br />',Zend_Locale_Format::toNumber($sizes[0]),' x ',Zend_Locale_Format::toNumber($sizes[1]),
								'<br />',$date->setTimestamp(filemtime($file))->toString();
						} ?></div>
					</td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>