<?php
/**
 * Created S/04/10/2014
 * Updated D/24/12/2023
 *
 * Copyright 2008-2025 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * Copyright 2019-2023 | Fabrice Creuzot <fabrice~cellublue~com>
 * https://github.com/luigifab/openmage-apijs
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$helper     = $this->helper('apijs');
$product    = Mage::registry('current_product');
$attributes = $product->getMediaAttributes();

$date = Mage::getSingleton('core/locale')->date();
$base = Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl();
$pid  = $product->getId();
$sid  = $product->getStoreId();
$hids = (int) date('His') + random_int(10000, 90000); // ids des input, toujours unique, même après ajax

$sortByStore = Mage::getStoreConfigFlag('apijs/general/sort_by_store');
if ($sortByStore)
	$stores = Mage::getResourceModel('core/store_collection');

$data    = $this->getImages($sortByStore);
$exclude = empty($sid) ? 'false' : '\''.$helper->escapeEntities($this->__('Automatically exclude these images from other store views'), true).'\'';

if (!empty($this->getRequest()->getParam('debug')))
	echo '<pre>',print_r($data, true),'</pre>';
?>

<div class="grid" id="apijsGallery">
	<table cellspacing="0" class="data border gallery">
		<colgroup>
			<col />
			<col />
			<?php foreach ($attributes as $attribute): ?>
				<?php if ($attribute->getIsText() === true) continue; ?>
				<col width="1" />
			<?php endforeach ?>
			<col width="1" />
			<col width="110px" />
		</colgroup>
		<thead>
			<tr class="headings">
				<th><?php echo $this->__('Image'),'<br /><span>',$this->__('[GLOBAL]'),'</span>' ?></th>
				<th><?php echo $this->__('Label and Sort order'),'<br /><span>',$this->__('[STORE VIEW]'),'</span>' ?></th>
				<?php foreach ($attributes as $code => $attribute): ?>
					<?php if ($attribute->getIsText() === true) continue; ?>
					<th class="attr" title="<?php echo $attribute->getId(),' ',$code ?>"><?php
						echo $attribute->getFrontend()->getLabel(),'<br /><span>',$this->getScopeLabel($attribute),'</span>';
					?></th>
				<?php endforeach ?>
				<th class="attr"><?php echo $this->__('Exclude'),'<br /><span>',$this->__('[STORE VIEW]'),'</span>' ?></th>
				<th class="last"></th>
			</tr>
			<tr class="filter">
				<th></th>
				<th>
					<?php if ($sortByStore): ?>
						<label>
							<select style="width:calc(100% - 1.5em);" class="filter no-changes" id="apijsFilter" onchange="apijsOpenMage.filter(this);">
								<option value="all"><?php echo $this->__('View All') ?></option>
								<option value="none"><?php echo $this->__('Collapse All') ?></option>
								<?php $prev = -1 ?>
								<?php foreach ($data['images'] as $image):
									$grp = $image->getData('apijs_group');
									if ($grp == $prev) continue;
								?>
									<option value="<?php echo $grp ?>" <?php echo (($sid > 0) && ($grp == ($sid * 100))) ? 'selected="selected"' : '' ?>><?php
										if ($grp < 1)
											echo '!?';
										else if (empty($store = $stores->getItemById($grp / 100)))
											echo $grp;
										else
											echo $grp,' / ',$store->getCode(),' / ',$store->getName();
									?></option>
									<?php $prev = $grp ?>
								<?php endforeach ?>
							</select>
						</label>
						<button type="button" class="slink filter" onclick="apijsOpenMage.filter('all');">X</button>
					<?php endif ?>
				</th>
				<?php foreach ($attributes as $code => $attribute): ?>
					<?php if ($attribute->getIsText() === true) continue; ?>
					<?php // si dans eav_attribute, attribute_model = xyz/source_xyz ?>
					<?php // $attribute = Xyz_Xyz_Model_Source_Xyz extends Mage_Catalog_Model_Resource_Eav_Attribute ?>
					<?php if ($attribute->getIsCheckbox() === true): ?>
						<th class="gallery_<?php echo $code ?>">
							<button type="button" class="slink filter" onclick="apijsOpenMage.filter(this);" data-reverse="1" data-state="0" data-text="<?php echo $helper->escapeEntities($this->__('Show'), true) ?>">
								<?php echo $this->__('Hide') ?>
							</button>
						</th>
					<?php else: ?>
						<th></th>
					<?php endif ?>
				<?php endforeach ?>
				<th class="gallery_disabled">
					<button type="button" class="slink filter" onclick="apijsOpenMage.filter(this);" data-state="0" data-text="<?php echo $helper->escapeEntities($this->__('Show'), true) ?>">
						<?php echo $this->__('Hide') ?>
					</button>
				</th>
				<th class="last"></th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<td colspan="<?php echo count($attributes) + 4 ?>">
					<button type="button" class="scalable save" onclick="apijsOpenMage.actionSave('<?php echo $this->getSaveUrl() ?>');">
						<span><span><?php echo $this->__('Save images') ?></span></span>
					</button>
					<button type="button" class="scalable add" onclick="apijsOpenMage.sendFiles(this.textContent, '<?php echo $this->getAddUrl() ?>', <?php echo $helper->getMaxSizes() ?>, '<?php echo implode(',', Mage::getSingleton('cms/wysiwyg_images_storage')->getAllowedExtensions('image')) ?>', <?php echo $exclude ?>);">
						<span><span><?php echo $this->__('Add one or multiple files') ?></span></span>
					</button>
					<?php $maxWidth = (int) Mage::getStoreConfig('catalog/product_image/max_dimension') ?>
					<p><?php echo $this->__('The added or removed images are automatically saved.') ?>
					<br /><?php echo $this->__('Maximum images width and height is <a %s>%s x %s pixels</a>.',
						'href="'.$this->getUrl('*/system_config/edit', ['section' => 'catalog']).'"',
						$helper->getNumber($maxWidth), $helper->getNumber($maxWidth)) ?></p>
				</td>
			</tr>
		</tfoot>
		<tbody class="album" id="slideshow.0">
			<tr>
				<td class="img">
					<div style="width:200px;"><?php echo $this->__('No image') ?></div>
				</td>
				<td></td>
				<?php foreach ($attributes as $code => $attribute): ?>
					<?php if ($attribute->getIsText() === true) continue; ?>
					<td>
						<?php // si dans eav_attribute, attribute_model = xyz/source_xyz ?>
						<?php // $attribute = Xyz_Xyz_Model_Source_Xyz extends Mage_Catalog_Model_Resource_Eav_Attribute ?>
						<?php if ($attribute->getIsCheckbox() !== true): ?>
							<?php if (empty($sid)): ?>
								<label>
									<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
									<input type="radio" name="apijs[<?php echo $code ?>]" id="inpt-<?php echo ++$hids ?>" value="no_selection" <?php
										echo (empty($product->getData($code)) || ($product->getData($code) == 'no_selection')) ?
											'checked="checked"' : '';
									?> class="check" id="inpt-<?php echo ++$hids ?>" />
								</label>
							<?php else: ?>
								<?php if (empty($data['globalValues'][$code]) || ($data['globalValues'][$code] == 'no_selection')): ?>
									<label>
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="checkbox" value="no_selection" <?php
											echo (empty($data['storeValues'][$code]) || ($data['globalValues'][$code] == 'no_selection')) ? 'checked="checked"' : '';
										?> disabled="disabled" class="check" id="inpt-<?php echo ++$hids ?>" />
									</label>
								<?php else: ?>
									<label style="visibility:hidden;">
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="checkbox" class="check" />
									</label>
								<?php endif ?>
								<label>
									<?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
									<input type="radio" name="apijs[<?php echo $code ?>]" value="no_selection" <?php
										echo (empty($data['storeValues'][$code]) || ($data['globalValues'][$code] == 'no_selection') || ($data['storeValues'][$code] == 'no_selection')) ? 'checked="checked"' : '';
									?> class="check" id="inpt-<?php echo ++$hids ?>" />
								</label>
							<?php endif ?>
						<?php endif ?>
					</td>
				<?php endforeach ?>
				<td></td>
				<td class="last">
					<?php if (count($data['images']) > 1): ?>
						<button type="button" class="slink remove" onclick="apijsOpenMage.removeAllAttachments('<?php echo $this->getRemoveUrl('all') ?>'); return false;"><?php echo $this->__('Remove all') ?></button>
					<?php endif ?>
				</td>
			</tr>
			<?php $i = 0; $prev = -1; ?>
			<?php foreach ($data['images'] as $image):
				$iid   = $image->getData('value_id');
				$path  = $image->getData('file');
				$file  = $helper->getCatalogProductImageDir().$path;
				$label = $helper->escapeEntities($image->getData('label'), true);
				$name  = $helper->escapeEntities(basename($file), true);
				$grp   = $image->getData('apijs_group');
			?>
				<?php if ($sortByStore && ($grp != $prev)): ?>
					<tr class="separ grp<?php echo $grp ?>" onclick="apijsOpenMage.filter('<?php echo $grp ?>');">
						<td colspan="<?php echo count($attributes) + 4 ?>">
							<?php
								if ($grp < 1)
									echo '!?';
								else if (empty($store = $stores->getItemById($grp / 100)))
									echo $grp;
								else
									echo $grp,' / ',$store->getCode(),' / ',$store->getName();
							?> / <?php
								$cnt = $data['counts'][$grp];
								if ($cnt <= 1)
									echo $this->__('%d image', $cnt);  // 0-1
								else if ($cnt <= 4)
									echo  $helper->_('%d images', $cnt); // 2-4
								else
									echo $this->__('%d images', $cnt); // 5+
							?>
						</td>
					</tr>
					<tr class="separ inf" onclick="apijsOpenMage.filter('<?php echo $grp ?>');">
						<td colspan="2"></td>
						<?php foreach ($attributes as $code => $attribute): ?>
							<?php if ($attribute->getIsText() === true) continue ?>
							<?php if ($attribute->getIsCheckbox() === true): ?>
								<td title="<?php echo $code ?>"></td>
							<?php else: ?>
								<td title="<?php echo $code ?>">
									<em>
										<?php if (empty($data['defaultValues'][$attribute->getId()][$grp / 100])): ?>
											!
										<?php else: ?>
											<?php echo $this->__('Yes') ?>
											<?php if ($data['defaultValues'][$attribute->getId()][$grp / 100] == $data['storeValues'][$code]): ?>
												<?php echo $this->__('here') ?>
											<?php endif ?>
										<?php endif ?>
									</em>
								</td>
							<?php endif ?>
						<?php endforeach ?>
						<td colspan="2"></td>
					</tr>
					<?php $prev = $grp ?>
				<?php endif ?>
				<tr id="attachmentId<?php echo $iid ?>" <?php echo ($sortByStore && ($sid > 0) && ($grp != ($sid * 100))) ? 'style="display:none;"' : '' ?>>
					<td class="img hgt" title="<?php echo $helper->escapeEntities($path, true) ?>">
						<?php if (is_file($file)):
							// <a> <img src srcset> <input>
							// l'image du lien = une image redimensionnée en cache
							// l'image de l'image = une miniature en cache
						?>
							<a href="<?php echo $helper->resizeImage($product, 'image', $path, 1200, 900, false) ?>" type="<?php echo mime_content_type($file) ?>" onclick="return false" id="slideshow.0.<?php echo $i++ ?>">
								<img src="<?php echo $helper->resizeImage($product, 'thumbnail', $path, 200, 150, true) ?>" srcset="<?php echo $helper->resizeImage($product, 'thumbnail', $path, 400, 300, true) ?> 2x" width="200" height="150" alt="<?php echo $label ?>" />
								<input type="hidden" value="<?php echo $name ?>|false|<?php echo $label ?>" />
							</a>
						<?php else: ?>
							<?php echo $this->__('File not found') ?>
						<?php endif ?>
					</td>
					<td>
						<div>
							<input type="hidden" name="apijs[<?php echo $iid ?>][file]" value="<?php echo $path ?>" />
							<div>
								<?php if (empty($sid)): ?>
									<label>
										<?php echo $this->__('Label') ?> / <?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="text" name="apijs[<?php echo $iid ?>][label]" value="<?php echo $label ?>" maxlength="250" class="input-text val" id="inpt-<?php echo ++$hids ?>" />
									</label>
								<?php else: ?>
									<label>
										<?php echo $this->__('Label') ?> / <?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
										<input type="checkbox" name="apijs[<?php echo $iid ?>][label]" value="$$" <?php
											echo $this->isUseGlobal($image, 'label', 'checked');
										?> class="check def inl" id="inpt-<?php echo ++$hids ?>" onchange="apijsOpenMage.checkVal(this);" />
									</label>
									<label>
										<input type="text" name="apijs[<?php echo $iid ?>][label]" value="<?php
											echo $helper->escapeEntities(($image->getData('label') != $image->getData('label_default')) ?
												$image->getData('label') : $image->getData('label_default'), true);
										?>" <?php
											echo $this->isUseGlobal($image, 'label', 'disabled');
										?> maxlength="250" class="input-text val" id="inpt-<?php echo ++$hids ?>" />
									</label>
								<?php endif ?>
							</div>
							<div>
								<?php if (empty($sid)): ?>
									<label>
										<?php echo $this->__('Sort Order') ?> / <?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="number" min="0" step="1" name="apijs[<?php echo $iid ?>][position]" value="<?php echo $image->getData('position') ?>" class="input-text position val" id="inpt-<?php echo ++$hids ?>" />
									</label>
								<?php else: ?>
									<label>
										<?php echo $this->__('Sort Order') ?> / <?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
										<input type="checkbox" name="apijs[<?php echo $iid ?>][position]" value="$$" <?php
											echo $this->isUseGlobal($image, 'position', 'checked');
										?> class="check def inl" id="inpt-<?php echo ++$hids ?>" onchange="apijsOpenMage.checkVal(this);" />
									</label>
									<label>
										<input type="number" min="0" step="1" name="apijs[<?php echo $iid ?>][position]" value="<?php echo $image->getData('position') ?>" <?php
											echo $this->isUseGlobal($image, 'position', 'disabled');
										?> class="input-text position val" id="inpt-<?php echo ++$hids ?>" />
									</label>
								<?php endif ?>
							</div>
							<?php foreach ($attributes as $code => $attribute): ?>
								<?php if ($attribute->getIsText() !== true) continue; ?>
								<div>
									<?php // si dans eav_attribute, attribute_model = xyz/source_xyz ?>
									<?php // $attribute = Xyz_Xyz_Model_Source_Xyz extends Mage_Catalog_Model_Resource_Eav_Attribute ?>
									<?php if (empty($sid)): ?>
										<label>
											<?php echo $attribute->getData('frontend_label') ?> / <?php echo trim($this->__('[GLOBAL]'), '[]') ?>
											<?php if ($attribute->getInputType() == 'number'): ?>
												<input type="number" min="0" step="1" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="<?php
													echo $helper->escapeEntities($image->getData($code), true);
												?>" class="input-text val" id="inpt-<?php echo ++$hids ?>" />
											<?php else: ?>
												<input type="text" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="<?php
													echo $helper->escapeEntities($image->getData($code), true);
												?>" class="input-text val" id="inpt-<?php echo ++$hids ?>" />
											<?php endif ?>
										</label>
									<?php else: ?>
										<label>
											<?php echo $attribute->getData('frontend_label') ?> / <?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
											<input type="checkbox" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="$$" <?php
												echo $this->isUseGlobal($image, $code, 'checked');
											?> class="check def inl" id="inpt-<?php echo ++$hids ?>" onchange="apijsOpenMage.checkVal(this);" />
										</label>
										<label>
											<?php if ($attribute->getInputType() == 'number'): ?>
												<input type="number" min="0" step="1" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="<?php
													echo $helper->escapeEntities(($image->getData($code) != $image->getData($code.'_default')) ? $image->getData($code) : $image->getData($code.'_default'), true);
												?>" <?php
													echo $this->isUseGlobal($image, $code, 'disabled');
												?> class="input-text val" id="inpt-<?php echo ++$hids ?>" />
											<?php else: ?>
												<input type="text" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="<?php
													echo $helper->escapeEntities(($image->getData($code) != $image->getData($code.'_default')) ? $image->getData($code) : $image->getData($code.'_default'), true);
												?>" <?php
													echo $this->isUseGlobal($image, $code, 'disabled');
												?> class="input-text val" id="inpt-<?php echo ++$hids ?>" />
											<?php endif ?>
										</label>
									<?php endif ?>
								</td>
							<?php endforeach ?>
						</div>
					</td>
					<?php foreach ($attributes as $code => $attribute): ?>
						<?php if ($attribute->getIsText() === true) continue; ?>
						<td class="gallery_<?php echo $code ?><?php echo (empty($sid) && ($grp > 99) && !empty($data['defaultValues'][$attribute->getId()][$grp / 100]) && ($data['defaultValues'][$attribute->getId()][$grp / 100] == $path)) ? ' mark selected-in-group-'.$grp : '' ?>">
 							<?php // si dans eav_attribute, attribute_model = xyz/source_xyz ?>
							<?php // $attribute = Xyz_Xyz_Model_Source_Xyz extends Mage_Catalog_Model_Resource_Eav_Attribute ?>
							<?php if ($attribute->getIsCheckbox() === true): ?>
								<?php if (empty($sid)): ?>
									<label>
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="checkbox" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="1" <?php
											echo empty($image->getData($code)) ? '' : 'checked="checked"';
										?> class="check" id="inpt-<?php echo ++$hids ?>" />
									</label>
								<?php else: ?>
									<label>
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="checkbox" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="$$" <?php
											echo $this->isUseGlobal($image, $code, 'checked');
										?> class="check def" id="inpt-<?php echo ++$hids ?>" onchange="apijsOpenMage.checkVal(this);" />
									</label>
									<label>
										<?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
										<input type="checkbox" name="apijs[<?php echo $iid ?>][<?php echo $code ?>]" value="1" <?php
											echo $image->getData($code) ? 'checked="checked"' : '';
										?> <?php
											echo $this->isUseGlobal($image, $code, 'disabled');
										?> class="check val" id="inpt-<?php echo ++$hids ?>" />
									</label>
								<?php endif ?>
							<?php else: ?>
								<?php if (empty($sid)): ?>
									<label>
										<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
										<input type="radio" name="apijs[<?php echo $code ?>]" value="<?php echo $path ?>" <?php
											echo ($product->getData($code) == $path) ? 'checked="checked"' : '';
										?> class="check" id="inpt-<?php echo ++$hids ?>" />
									</label>
								<?php else: ?>
									<?php if ($data['globalValues'][$code] == $path): ?>
										<label>
											<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
											<input type="checkbox" checked="checked" disabled="disabled" class="check" id="inpt-<?php echo ++$hids ?>" />
										</label>
									<?php else: ?>
										<label style="visibility:hidden;">
											<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
											<input type="checkbox" class="check" />
										</label>
									<?php endif ?>
									<label>
										<?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
										<input type="radio" name="apijs[<?php echo $code ?>]" value="<?php echo $path ?>" <?php
											echo ($data['storeValues'][$code] == $path) ? 'checked="checked"' : '';
										?> class="check" id="inpt-<?php echo ++$hids ?>" />
									</label>
								<?php endif ?>
							<?php endif ?>
						</td>
					<?php endforeach ?>
					<td class="gallery_disabled">
						<?php if (empty($sid)): ?>
							<label>
								<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
								<input type="checkbox" name="apijs[<?php echo $iid ?>][disabled]" value="1" <?php
									echo $image->getData('disabled') ? 'checked="checked"' : '';
								?> class="check val" id="inpt-<?php echo ++$hids ?>" />
							</label>
						<?php else: ?>
							<label>
								<?php echo trim($this->__('[GLOBAL]'), '[]') ?>
								<input type="checkbox" name="apijs[<?php echo $iid ?>][disabled]" value="$$" <?php
									echo $this->isUseGlobal($image, 'disabled', 'checked');
								?> class="check def" id="inpt-<?php echo ++$hids ?>" onchange="apijsOpenMage.checkVal(this);" />
							</label>
							<label>
								<?php echo trim($this->__('[STORE VIEW]'), '[]') ?>
								<input type="checkbox" name="apijs[<?php echo $iid ?>][disabled]" value="1" <?php
									echo $image->getData('disabled') ? 'checked="checked"' : '';
								?> <?php
									echo $this->isUseGlobal($image, 'disabled', 'disabled');
								?> class="check val" id="inpt-<?php echo ++$hids ?>" />
							</label>
						<?php endif ?>
					</td>
					<td class="last">
						<?php if (is_file($file)): ?>
							<a href="<?php echo $base,$path ?>" type="<?php echo mime_content_type($file) ?>" download=""><?php echo $this->__('Download') ?></a>
						<?php else: ?>
							<a href="<?php echo $base,$path ?>" style="font-style:italic;" onclick="return false;"><?php echo $this->__('Download') ?></a>
						<?php endif ?>
						<br /><button type="button" class="slink remove" onclick="apijsOpenMage.removeAttachment('<?php echo $this->getRemoveUrl($iid, basename($path)) ?>'); return false;"><?php echo $this->__('Remove') ?></button>

						<div style="margin-top:1em;"><?php if (is_file($file)) {
							if (str_ends_with($file, '.svg')) {
								echo $helper->getNumberToHumanSize(filesize($file)),
									'<br />',$date->setTimestamp(filemtime($file))->toString();
							}
							else {
								$sizes = (array) getimagesize($file); // (yes)
								echo $helper->getNumberToHumanSize(filesize($file)),
									'<br />',$helper->getNumber($sizes[0]),' x ',$helper->getNumber($sizes[1]),
									'<br />',$date->setTimestamp(filemtime($file))->toString();
							}
						} ?></div>
					</td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>