<?php
/**
 * Created J/01/12/2011
 * Updated S/22/03/2014
 * Version 20
 *
 * Copyright 2011-2014 | Fabrice Creuzot (luigifab) <code~luigifab~info>
 * https://redmine.luigifab.info/projects/magento/wiki/apijs
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */
?>

<ul style="padding:1em; border:1px solid gray; background-color:#CCC; list-style:none;">
	<li><?php echo $this->__('Documentation: <a %s>apijs</a>, <a %s%s>module</a>, <a %s>translation</a>', 'href="http://www.luigifab.info/apijs/index.php" onclick="window.open(this.href); return false;"', 'href="https://redmine.luigifab.info/projects/magento/wiki/Apijs-', '" onclick="window.open(this.href); return false;"', 'href="https://redmine.luigifab.info/projects/apijs/wiki" onclick="window.open(this.href); return false;"') ?></li>
	<li><?php echo $this->__('Version:'),' <strong>',$this->helper('apijs')->getVersion(),'</strong>' ?></li>
	<li><?php echo $this->__('State:'),' <strong>',$this->helper('apijs')->getStatus('frontend'),'</strong>' ?></li>
	<?php if (Mage::getStoreConfig('apijs/general/frontend') === '1'): ?>
		<li>
			<?php echo $this->__('Examples:') ?>
			<button onclick="apijs.dialog.dialogInformation('<?php echo $this->__('PHP manual') ?>','<?php echo addslashes($this->__('It is important to note that just because the mail was accepted for delivery, it doesn\'t mean the mail will actually reach the intended destination.')) ?>');" type="button">1</button>
			<button onclick="apijs.dialog.dialogInformation('<?php echo $this->__('Surprise!') ?>','[p]<?php echo addslashes($this->__('You are looking this video without proprietary extension thanks to the new [em]video[/em] tag included in the [strong]HTML 5[/strong] format.')) ?>[/p][p]<?php echo addslashes($this->__('Website: %s', '[a href=\'http://www.luigifab.info/\' class=\'popup\']www.luigifab.info[/a]')) ?>[/p]');" type="button">2</button>
			<button onclick="apijs.dialog.dialogInformation('<?php echo $this->__('Surprise!') ?>','[p]<?php echo addslashes($this->__('See the title on emoicons for help...')) ?>[/p][p style=\'width:75%; text-align:center;\'] :D - :) - :p - :( - ;) - :lol - 8) - :@ - (6) - :o - :s - :| - :/ - (L) - (!) - (?) - (i) - (u) - (y) - (n) [/p]','notransition warning');" type="button">3</button>
		</li>
	<?php endif ?>
</ul>