<?php
/**
 * Created M/15/01/2013
 * Updated V/21/03/2014
 * Version 5
 *
 * Copyright 2013-2014 | Fabrice Creuzot (luigifab) <code~luigifab~info>
 * https://redmine.luigifab.info/projects/magento/wiki/apijs
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$product = $this->getProduct();
$class = (Mage::getStoreConfig('apijs/gallery/hoverload') === '1') ? 'gallery hoverload' : 'gallery';
?>

<?php if ($product->getImage()): ?>
	<div class="<?php echo $class ?>" id="slideshow.0">
		<?php echo $this->getPhoto() ?>
		<?php if (count($this->getGalleryImages()) > 1): ?>
			<ul>
				<?php foreach ($this->getGalleryImages() as $image): ?>
					<li><?php echo $this->getThumbnail($image, $image->getLabel()) ?></li>
				<?php endforeach ?>
			</ul>
		<?php endif ?>
	</div>
<?php endif ?>