<?php
/**
 * Created D/20/11/2011
 * Updated D/01/06/2014
 * Version 30
 *
 * Copyright 2008-2014 | Fabrice Creuzot (luigifab) <code~luigifab~info>
 * https://redmine.luigifab.info/projects/magento/wiki/apijs
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */
?>

<ul style="list-style:none; line-height:120%;">
	<li><?php echo $this->__('Documentation: <a %s>apijs</a>, <a %s%s>module</a>, <a %s>translation</a>', 'href="http://www.luigifab.info/apijs/index.php" onclick="window.open(this.href); return false;"', 'href="https://redmine.luigifab.info/projects/magento/wiki/Apijs-', '" onclick="window.open(this.href); return false;"', 'href="https://redmine.luigifab.info/projects/apijs/wiki" onclick="window.open(this.href); return false;"') ?></li>
	<li><?php echo $this->__('Version:'),' <strong>',$this->helper('apijs')->getVersion(),'</strong>' ?></li>
	<li><?php echo $this->__('State:'),' <strong>',$this->helper('apijs')->getStatus('backend'),'</strong>' ?></li>
	<?php if (Mage::getStoreConfig('apijs/general/backend') === '1'): ?>
		<li>
			<?php echo $this->__('Examples:') ?>
			<button onclick="apijs.dialog.dialogInformation('<?php echo $this->__('PHP manual') ?>','<?php echo addslashes($this->__('It is important to note that just because the mail was accepted for delivery, it doesn\'t mean the mail will actually reach the intended destination.')) ?>');" type="button">1</button>
			<button onclick="apijs.dialog.dialogInformation('<?php echo $this->__('Surprise!') ?>','[p]<?php echo addslashes($this->__('You are looking this video without proprietary extension thanks to the new [em]video[/em] tag included in the [strong]HTML 5[/strong] format.')) ?>[/p][p]<?php echo addslashes($this->__('Website: %s', '[a href=\'http://www.luigifab.info/\' class=\'popup\']www.luigifab.info[/a]')) ?>[/p]');" type="button">2</button>
			<button onclick="apijs.dialog.dialogInformation('<?php echo $this->__('Surprise!') ?>','[p]<?php echo addslashes($this->__('See the title on emoicons for help...')) ?>[/p][p style=\'width:75%; text-align:center;\'] :D - :) - :p - :( - ;) - :lol - 8) - :@ - (6) - :o - :s - :| - :/ - (L) - (!) - (?) - (i) - (u) - (y) - (n) [/p]','notransition warning');" type="button">3</button>
		</li>
	<?php endif ?>
</ul>

<?php if (Mage::getStoreConfig('apijs/general/frontend') === '1'): ?>
	<p style="margin-top:1em;"><?php echo $this->__('You can use one of this lines to test this module on the frontend.') ?></p>
	<pre style="margin-bottom:0.8em; font-size:0.9em; line-height:1.4em;"><code>{{block type="core/template" template="luigifab/apijs/demo.phtml"}}
&lt;block type="core/template" template="luigifab/apijs/demo.phtml" /&gt;
&lt;?php echo $this->getLayout()->createBlock('core/template')->setTemplate('luigifab/apijs/demo.phtml')->toHtml() ?&gt;
</code></pre>
<?php endif ?>

<hr style="margin:1em 0; border:none; border-top:1px solid #BBB;" />