<?php
/**
 * Created S/04/10/2014
 * Updated M/08/11/2016
 *
 * Copyright 2008-2017 | Fabrice Creuzot (luigifab) <code~luigifab~info>
 * https://redmine.luigifab.info/projects/magento/wiki/apijs
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$product = Mage::registry('current_product');
$attributes = $product->getMediaAttributes();
$storeId = intval($this->getRequest()->getParam('store', 0));

$images = $product->getMediaGalleryImages();
$images = (!is_null($images)) ? $images : array();

$i = 0;
?>

<div class="grid" id="apijsGallery">
	<table cellspacing="0" cellpadding="0" class="data border gallery">
		<thead>
			<tr class="headings">
				<th><?php echo $this->__('Image'),'<br /><small>',$this->__('[GLOBAL]'),'</small>' ?></th>
				<th><?php echo $this->__('Label and Sort order'),'<br /><small>',$this->__('[STORE VIEW]'),'</small>' ?></th>
				<?php foreach ($attributes as $attribute): ?>
					<th class="type"><?php echo $attribute->getFrontend()->getLabel(),'<br /><small>',$this->getScopeLabel($attribute),'</small>' ?></th>
				<?php endforeach ?>
				<th class="type"><?php echo $this->__('Exclude'),'<br /><small>',$this->__('[STORE VIEW]'),'</small>' ?></th>
				<th style="width:110px;" class="last"></th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<td colspan="<?php echo count($attributes) + 2 ?>">
					<p><?php echo $this->__('The added or deleted photos are automatically saved.<br /><strong>Warning:</strong> any modification on photos must be saved via the appropriate save button.') ?></p>
				</td>
				<td colspan="2" class="last">
					<button type="button" class="scalable add" onclick="apijsSendFile('<?php echo $this->getAddUrl($product->getId(), $storeId) ?>', <?php echo $this->getMaxSize() ?>);"><?php echo $this->__('Add a photo') ?></button>
				</td>
			</tr>
		</tfoot>
		<tbody class="album" id="slideshow.0">
			<?php foreach ($images as $image):
				$file = Mage::getSingleton('catalog/product_media_config')->getBaseMediaPath().$image->getFile();
			?>
				<tr id="attachmentId<?php echo $image->getId() ?>">
					<td>
						<?php if (is_file($file) && is_readable($file)):

							$ressource = $this->helper('catalog/image')->init($product, 'image', $image->getFile());

							// redimensionne l'image si l'image dépasse 1200x900 px
							// ne fait rien dans les autres cas (utilise l'image source)
							$sizes = getimagesize($file);
							if ($sizes[0] > 1200)
								$ressource->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize(1200, null);
							else if ($sizes[1] > 900)
								$ressource->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize(null, 900);

							// <a> <img> <input>
							// l'image du lien = une image redimensionnée en cache
							// l'image de l'image = une miniature en cache
						?>
							<a href="<?php echo $ressource ?>" type="<?php echo mime_content_type($file) ?>" onclick="return false;" id="slideshow.0.<?php echo $i++ ?>">
								<img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $image->getFile())->resize(200, 150) ?>" width="200" height="150" alt="<?php echo $image->getLabel() ?>" />
								<input type="hidden" value="false|false|<?php echo $image->getLabel() ?>" />
							</a>
						<?php else: ?>
							<?php echo $this->__('File not found') ?>
						<?php endif ?>
					</td>
					<td>
						<span><?php echo $this->__('Label') ?></span>
						<?php if ($storeId > 0): /* ?>
							<span><?php echo $this->__('[GLOBAL]') ?></span>
							<input type="text" value="<?php echo htmlentities($image->getLabelDefault()) ?>" disabled="disabled" class="input-text" />
							<span><?php echo $this->__('[STORE VIEW]') ?></span>
							<input type="text" name="apijs-label" value="<?php echo htmlentities($image->getLabel()) ?>" maxlength="200" class="input-text" />
							<a class="default"><?php echo $this->__('Use default value') ?></a>
						<?php */ else: ?>
							<input type="text" name="apijs-label" value="<?php echo htmlentities($image->getLabel()) ?>" maxlength="200" class="input-text" onchange="apijsEnableButtonSave(this, event);" onkeyup="apijsEnableButtonSave(this, event);" />
						<?php endif ?>
						<span><?php echo $this->__('Sort Order') ?></span>
						<?php if ($storeId > 0): /* ?>
							<span><?php echo $this->__('[GLOBAL]') ?></span>
							<input type="number" value="<?php echo $image->getPositionDefault() ?>" disabled="disabled" class="input-text" />
							<span><?php echo $this->__('[STORE VIEW]') ?></span>
							<input type="number" min="1" name="apijs-position" value="<?php echo $image->getPosition() ?>" maxlength="5" class="input-text" />
							<a class="default"><?php echo $this->__('Use default value') ?></a>
						<?php */ else: ?>
							<input type="number" min="1" name="apijs-position" value="<?php echo $image->getPosition() ?>" maxlength="5" class="input-text" onchange="apijsEnableButtonSave(this, event);" onkeyup="apijsEnableButtonSave(this, event);" />
						<?php endif ?>
					</td>
					<?php foreach ($attributes as $attribute): ?>
						<td>
							<?php if ($storeId > 0): /* ?>
								<span><?php echo $this->__('[GLOBAL]') ?></span>
								<input type="radio" <?php echo ($product->getData($attribute->getAttributeCode()) === $image->getFile()) ? 'checked="checked"' : ''; ?> disabled="disabled" />
								<?php if (!$attribute->isScopeGlobal()): ?>
									<span><?php echo $this->__('[STORE VIEW]') ?></span>
									<input type="radio" name="apijs-<?php echo $attribute->getAttributeCode() ?>" <?php echo ($product->getData($attribute->getAttributeCode()) === $image->getFile()) ? 'checked="checked"' : ''; ?> />
								<?php endif ?>
							<?php */ else: ?>
								<input type="radio" name="apijs-<?php echo $attribute->getAttributeCode() ?>" <?php echo ($product->getData($attribute->getAttributeCode()) === $image->getFile()) ? 'checked="checked"' : ''; ?> onchange="apijsEnableButtonSave(this, event);" onkeyup="apijsEnableButtonSave(this, event);" />
							<?php endif ?>
						</td>
					<?php endforeach ?>
					<td>
						<?php if ($storeId > 0): /* ?>
							<span><?php echo $this->__('[GLOBAL]') ?></span>
							<input type="checkbox" <?php echo ($image->getDisabledDefault()) ? 'checked="checked"' : ''; ?> disabled="disabled" />
							<span><?php echo $this->__('[STORE VIEW]') ?></span>
							<input type="checkbox" name="apijs-disabled" <?php echo ($image->getDisabled()) ? 'checked="checked"' : ''; ?> />
						<?php */ else: ?>
							<input type="checkbox" name="apijs-disabled" <?php echo ($image->getDisabled()) ? 'checked="checked"' : ''; ?> onchange="apijsEnableButtonSave(this, event);" onkeyup="apijsEnableButtonSave(this, event);" />
						<?php endif ?>
					</td>
					<td class="last">
						<button type="button" <?php echo (is_file($file)) ? '' : 'disabled="disabled"' ?> class="scalable back" onclick="setLocation('<?php echo $this->getDownloadUrl($product->getId(), $image->getId()) ?>');"><?php echo $this->__('Download') ?></button>
						<button type="button" disabled="disabled" class="scalable save ici" onclick="apijsActionSave(this, '<?php echo $this->getSaveUrl($product->getId(), $storeId, $image->getId()) ?>');"><?php echo $this->__('Save') ?></button>
						<button type="button" class="scalable delete" onclick="apijsDeleteAttachment('<?php echo $this->getDeleteUrl($product->getId(), $image->getId()) ?>');"><?php echo $this->__('Remove') ?></button>
						<div style="margin-top:1em;"><?php if (is_file($file) && is_readable($file)) {
							$size = filesize(Mage::getSingleton('catalog/product_media_config')->getBaseMediaPath().$image->getFile());
							echo $this->helper('apijs')->getNumberToHumanSize($size);
						} ?></div>
					</td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>