<?php
/**
 * Created M/15/01/2013
 * Updated M/20/08/2019
 *
 * Copyright 2008-2020 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * https://www.luigifab.fr/magento/apijs
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

if (is_object($this->getGalleryImages())):
	$images = [];
	foreach ($this->getGalleryImages() as $image) {
		if (is_file($image->getData('path')))
			$images[] = $image;
	}
	$total = count($images);
	$id = 0;
?>
	<div class="<?php echo Mage::getStoreConfigFlag('apijs/gallery/hoverload') ? 'gallery hoverload' : 'gallery' ?>" id="slideshow.0">
		<?php echo $this->getBaseImage($images, $total) ?>
		<?php if ($total > 1): ?>
			<ul>
				<?php foreach ($images as $image): ?>
					<li><?php echo $this->getThumbnail($image, $id++) ?></li>
				<?php endforeach ?>
			</ul>
		<?php endif ?>
	</div>
<?php endif ?>